training_inputs=[[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]]
expected_training_outputs=[[0.0], [1.0], [1.0], [0.0]]
test_inputs=[[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]]
expected_test_outputs=[[0.0], [1.0], [1.0], [0.0]]